.TH "ConvexHull" 3 "Thu Oct 8 2015" "Version 1.1" "Proyecto Individual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConvexHull \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConvexHull\fP (\fBPoint2D\fP)"
.br
.ti -1c
.RI "\fBConvexHull\fP (\fBPoint2D\fP, \fBHE_face\fP *)"
.br
.ti -1c
.RI "\fBConvexHull\fP (const \fBConvexHull\fP &obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHE_face\fP * \fBconvexhull\fP"
.br
.ti -1c
.RI "\fBPoint2D\fP \fBpoints\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Proyecto Individual from the source code\&.
