.TH "HE_edge" 3 "Thu Oct 8 2015" "Version 1.1" "Proyecto Individual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HE_edge \- 
.PP
La clase \fBHE_edge\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HE_edge\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHE_edge\fP ()"
.br
.RI "\fIMétodo Constructor\&. \fP"
.ti -1c
.RI "\fBHE_edge\fP (\fBHE_vert\fP *, \fBHE_edge\fP *, \fBHE_face\fP *, \fBHE_edge\fP *)"
.br
.RI "\fIMétodo Constructor con parametros de entrada\&. \fP"
.ti -1c
.RI "\fB~HE_edge\fP ()"
.br
.RI "\fIMétodo Destructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHE_vert\fP * \fBvert\fP"
.br
.RI "\fIContiene la dirección del vértice perteneciente al Medio Borde\&. \fP"
.ti -1c
.RI "\fBHE_edge\fP * \fBpareja\fP"
.br
.RI "\fIContiene la dirección de la otra mitad del Medio Borde\&. \fP"
.ti -1c
.RI "\fBHE_face\fP * \fBface\fP"
.br
.RI "\fIContiene la dirección de la cara que contiene al Medio Borde\&. \fP"
.ti -1c
.RI "\fBHE_edge\fP * \fBnext\fP"
.br
.RI "\fIContiene la dirección de un medio borde adyacente al Medio Borde\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBHE_edge\fP\&. 

Esta clase representa un Medio Borde\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HE_edge::HE_edge ()"

.PP
Método Constructor\&. Este método contruye el Medio Borde\&. 
.SS "HE_edge::HE_edge (\fBHE_vert\fP *vert, \fBHE_edge\fP *pareja, \fBHE_face\fP *face, \fBHE_edge\fP *next)"

.PP
Método Constructor con parametros de entrada\&. Construye un Medio Borde utilizando datos anteriores\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Proyecto Individual from the source code\&.
