.TH "HE_vert" 3 "Thu Oct 8 2015" "Version 1.1" "Proyecto Individual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HE_vert \- 
.PP
La clase \fBHE_vert\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HE_vert\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHE_vert\fP (void)"
.br
.RI "\fIMetodo Constructor sin parámetros\&. \fP"
.ti -1c
.RI "\fBHE_vert\fP (\fBPoint2D\fP, \fBHE_edge\fP *)"
.br
.RI "\fIMétodo Constructor con parámetros\&. \fP"
.ti -1c
.RI "\fB~HE_vert\fP (void)"
.br
.RI "\fIMétodo Destructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint2D\fP \fBpoint\fP"
.br
.RI "\fIUna variable publica point (\fBPoint2D\fP) \fP"
.ti -1c
.RI "\fBHE_edge\fP * \fBedge\fP"
.br
.RI "\fIUna variable pública edge(HE_edge *) \fP"
.in -1c
.SH "Detailed Description"
.PP 
La clase \fBHE_vert\fP\&. 

Esta clase implementa un vertice\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HE_vert::HE_vert (\fBPoint2D\fPpoint, \fBHE_edge\fP *edge)"

.PP
Método Constructor con parámetros\&. Este constructor asigna los valores de las cordenadas del punto y la dirección de memoria del siguiente Medio Borde\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBHE_edge\fP* HE_vert::edge"

.PP
Una variable pública edge(HE_edge *) Esta variable contiene la direccion de memoria del proximo Medio Borde\&. 
.SS "\fBPoint2D\fP HE_vert::point"

.PP
Una variable publica point (\fBPoint2D\fP) Esta variable contiene la coordenada en donde se encuentra el punto\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Proyecto Individual from the source code\&.
